version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  musclr-client: # name of the first service
    build: musclr-client # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forwarding

  musclr-server: #name of the second service
    build: musclr-server # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forwarding
    links:
      - mongodb # link this service to the database service

  mongodb: # name of the third service
    image: mongo:3 # specify image to build container from
    ports:
      - "27017:27017" # specify port forwarding

  mongo-seed:
    build: mongo-seed
    links:
      - mongodb